In [ ]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

In [ ]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [ ]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [ ]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [ ]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [ ]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [ ]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [ ]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

In [ ]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [ ]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

In [ ]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [ ]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x=2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [ ]:
x=50
seq(0,x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [ ]:
x=seq(1,50,1/2)

In [ ]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

In [ ]:
x=c(9,8,7,6)
ind=seq(along=x)
ind

[1] 1 2 3 4

In [ ]:
x[ind[2]]

[1] 8

In [ ]:
Sys.time()

[1] "2026-09-03 09:00:26 UTC"

In [ ]:
Sys.Date()

[1] "2026-09-03"

In [ ]:
seq(as.Date("2017-01-01"),by="days", length=6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [ ]:
seq(as.Date("2017-01-01"),by="months",length=6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [ ]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [ ]:
startdate = as.Date("2016-1-1")

In [ ]:
enddate=as.Date("2017-1-1")

In [ ]:
out=seq(enddate,startdate,by="-1 month")

In [ ]:
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
letters[1:3]

[1] "a" "b" "c"

In [ ]:
letters[3:1]

[1] "c" "b" "a"

In [ ]:
letters[21:23]

[1] "u" "v" "w"

In [ ]:
letters[2]

[1] "b"

In [ ]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
LETTERS[1:3]

[1] "A" "B" "C"

In [ ]:
LETTERS[3:1]

[1] "C" "B" "A"

In [ ]:
LETTERS[21:23]

[1] "U" "V" "W"

In [ ]:
LETTERS[2]

[1] "B"

In [ ]:
help("rep")

In [ ]:
rep(3.5,times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

In [ ]:
rep(1:4,2)

[1] 1 2 3 4 1 2 3 4

In [ ]:
x=1:4
x

[1] 1 2 3 4

In [ ]:
rep(x,times=3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

In [ ]:
rep(x,each=3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [ ]:
rep(1:4, each = 2)

[1] 1 1 2 2 3 3 4 4

In [ ]:
 rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, times = 3, each = 2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
ans = seq(from=2, to=8, by=2)

In [ ]:
ans

[1] 2 4 6 8

In [ ]:
rep(1:4,ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

In [ ]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(x,3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [ ]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [ ]:
rep(c("apple", "banana", "cake"), 2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [ ]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [ ]:
rep(2, length=5)

[1] 2 2 2 2 2

In [ ]:
rep(c(2,3),length=5)

[1] 2 3 2 3 2

In [ ]:
rep(c(2,3,4), length=5)

[1] 2 3 4 2 3

In [ ]:
rep("apple", length=5)

[1] "apple" "apple" "apple" "apple" "apple"

In [ ]:
rep(c("a", "b", "c"), length=2)

[1] "a" "b"

In [ ]:
 rep(c("a", "b", "c"), length=5)

[1] "a" "b" "c" "a" "b"

In [ ]:
 y = c(8,5,7,6)
 y

[1] 8 5 7 6

In [ ]:
 sort(y)

[1] 5 6 7 8

In [ ]:
sort(y, decreasing = TRUE)

[1] 8 7 6 5

In [ ]:
y = c(9,8,5,7,6)
y

[1] 9 8 5 7 6

In [ ]:
order(y)

[1] 3 5 4 2 1

In [ ]:
order(y, decreasing = TRUE)

[1] 1 2 4 5 3

In [ ]:
mode(2.432)

[1] "numeric"

In [ ]:
mode(c(3,4,5,6,7,8))

[1] "numeric"

In [ ]:
mode("India")

[1] "character"

In [ ]:
mode(c("India", "CANADA"))

[1] "character"

In [ ]:
mode(factor(c("UP", "MP")) )

[1] "numeric"

In [ ]:
mode(list("India", "USA"))

[1] "list"

In [ ]:
mode(print)

[1] "function"

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2= matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [ ]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [ ]:
x1[2,1] = "hello"
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2= matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [ ]:
matlist=list(x1,x2)

In [ ]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [ ]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1 = list( c("water", "juice", "lemonade"),
rep(1:4, each=2), matrix(data=5:8, nrow=2,
ncol=2, byrow=T) )

In [ ]:
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [ ]:
z1[1][2]

[[1]]
NULL

In [ ]:
z1[[1]][2]

[1] "juice"