In [1]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [2]:
2^3

[1] 8

In [3]:
2**3

[1] 8

In [4]:
2^0.5

[1] 1.414214

In [5]:
2**0.5

[1] 1.414214

In [6]:
2^-0.5

[1] 0.7071068

In [7]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [8]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [9]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [10]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [11]:
2 %/% 2

[1] 1

In [12]:
5 %/% 2

[1] 2

In [13]:
7 %/% 3

[1] 2

In [14]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [15]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [16]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [17]:
2 %% 2

[1] 0

In [18]:
3 %% 2

[1] 1

In [19]:
7 %% 3

[1] 1

In [20]:
7 %% 4

[1] 3

In [21]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [22]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [23]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [24]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [25]:
max( c(1.2, 3.4, -7.8) )

[1] 3.4

In [26]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [27]:
min( c(1.2, 3.4, -7.8) )

[1] -7.8

In [28]:
mean(2, 3, 4)

[1] 2

In [29]:
mean(c(2, 3, 4))

[1] 3

In [30]:
abs(-4)

[1] 4

In [31]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

In [32]:
sqrt(4)

[1] 2

In [33]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

In [34]:
sum(c(2,3,5,7))

[1] 17

In [35]:
prod(c(2,3,5,7))

[1] 210

In [36]:
round(1.23)

[1] 1

In [37]:
round(1.83)

[1] 2

In [38]:
log(10)

[1] 2.302585

In [39]:
log(exp(1))

[1] 1

In [40]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [41]:
log10(10)

[1] 1

In [42]:
log10(100)

[1] 2

In [43]:
log10(c(10, 100, 1000))

[1] 1 2 3

In [44]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [45]:
x2 = x1^2
x2

[1]  1  4  9 16

In [46]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [47]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

In [48]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8) )
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [49]:
x[3,2]

[1] 7

In [50]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [51]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [52]:
y = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [53]:
dim(x)

[1] 4 2

In [54]:
nrow(x)

[1] 4

In [55]:
ncol(x)

[1] 2

In [56]:
mode(x)

[1] "numeric"

In [57]:
attributes(x)

$dim
[1] 4 2

In [58]:
help("matrix")

In [59]:
is.matrix(as.matrix(1:10))

[1] TRUE

In [60]:
data(warpbreaks)

In [61]:
!is.matrix(warpbreaks)

[1] TRUE

In [62]:
warpbreaks[1:10,]

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

In [63]:
as.matrix(warpbreaks[1:10,])

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

In [64]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
5*x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [65]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x/2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [66]:
x = matrix( nrow=4, ncol=3, data=c(1:12) )
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [67]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [68]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [69]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [70]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [71]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [72]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [73]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [74]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [75]:
rowSums(x)

[1]  6  8 10 12

In [76]:
colSums(x)

[1] 10 26

In [77]:
rowMeans(x)

[1] 3 4 5 6

In [78]:
colMeans(x)

[1] 2.5 6.5

In [79]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [80]:
x[3,]

[1] 7 8 9

In [81]:
x[,2]

[1]  2  5  8 11 14

In [82]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [83]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [84]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x+5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [85]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [86]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [87]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [88]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [89]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [90]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [91]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [92]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [93]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [94]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [95]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [96]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [97]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [98]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [99]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [100]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [102]:
x = c(8,18)
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [103]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [104]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [105]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

In [108]:
x = c(8,18)
(x < 10) & (x > 2)

[1]  TRUE FALSE

In [109]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

In [110]:
x = 1:6
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [111]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [112]:
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [113]:
x[(x > 2) | (x < 5)]

[1] 1 2 3 4 5 6

In [115]:
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [116]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

In [117]:
x = TRUE
y = FALSE
x & y

[1] FALSE

In [118]:
x | y

[1] TRUE

In [119]:
!x

[1] FALSE

In [120]:
x = 5
Logical1 = (x > 2)
Logical1
is.logical(Logical1)

[1] TRUE

[1] TRUE

In [121]:
Logical2 = (x < 10)
Logical2
is.logical(Logical2)

[1] TRUE

[1] TRUE

In [122]:
Logical3 = (x != 5)
Logical3
is.logical(Logical3)

[1] FALSE

[1] TRUE

In [123]:
Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)

[1] FALSE

[1] TRUE

In [124]:
Logical5 = (3*x <20)
Logical5
is.logical(Logical5)

[1] TRUE

[1] TRUE

In [125]:
8 > 7

[1] TRUE

In [126]:
7 < 5

[1] FALSE

In [127]:
7 > 7

[1] FALSE

In [128]:
7 >= 7

[1] TRUE

In [129]:
8 < 8

[1] FALSE

In [130]:
8 <= 8

[1] TRUE

In [131]:
8 != 9

[1] TRUE

In [132]:
9 != 9

[1] FALSE

In [133]:
7 == 7

[1] TRUE

In [134]:
7 == 8

[1] FALSE

In [135]:
x = TRUE
!x

[1] FALSE

In [136]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x > y

[1] FALSE FALSE FALSE

In [137]:
x < y

[1] TRUE TRUE TRUE

In [138]:
x != y

[1] TRUE TRUE TRUE

In [139]:
x == y

[1] FALSE FALSE FALSE

In [140]:
isTRUE(8 < 6)

[1] FALSE

In [141]:
isTRUE(8 > 6)

[1] TRUE

In [142]:
isFALSE(5 < 8)

[1] FALSE

In [143]:
isFALSE(5 > 8)

[1] TRUE