Week 3

Powers, functions and matrices

Vector addition

In [1]:
c(2, 3, 5, 7) + c(-2, -3, -5, 8)

[1]  0  0  0 15

Powers

In [2]:
2^3
2**3
2^0.5
2^-0.5

[1] 8

[1] 8

[1] 1.414214

[1] 0.7071068

In [3]:
x = c(2, 3, 5, 7)
x^2
x^c(2, 3)
c(1, 2, 3, 4, 5, 6)^c(2, 3, 4)
# This one gives a recycling warning.
x^c(2, 3, 4)

[1]  4  9 25 49

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Warning message in x^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

Integer division and remainder

In [4]:
5 %/% 2
7 %/% 3
7 %% 3
7 %% 4

[1] 2

[1] 2

[1] 1

[1] 3

In [5]:
x %/% 2
x %/% c(2, 3)
x %% 2
x %% c(2, 3)

[1] 1 1 2 3

[1] 1 1 2 2

[1] 0 1 1 1

[1] 0 0 1 1

In [6]:
# Unequal recycling gives warnings here too.
c(2, 3, 5) %/% c(2, 3)
c(2, 3, 5) %% c(2, 3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

Maximum, minimum and mean

In [7]:
x = c(1.2, 3.4, -7.8)
max(x)
min(x)
mean(c(2, 3, 4))
# Put the values together before finding the mean.
mean(2, 3, 4)

[1] 3.4

[1] -7.8

[1] 3

[1] 2

Built-in functions

In [8]:
abs(c(-1, -2, -3, 4, 5))
sqrt(c(4, 9, 16, 25))
sum(c(2, 3, 5, 7))
prod(c(2, 3, 5, 7))

[1] 1 2 3 4 5

[1] 2 3 4 5

[1] 17

[1] 210

In [9]:
round(c(1.23, 1.83))
round(1.2345, digits = 2)
floor(c(1.23, 1.83))
ceiling(c(1.23, 1.83))

[1] 1 2

[1] 1.23

[1] 1 1

[1] 2 2

In [10]:
log(c(10, 100, 1000))
log10(c(10, 100, 1000))
log2(c(2, 4, 8))
exp(1)
log(exp(1))

[1] 2.302585 4.605170 6.907755

[1] 1 2 3

[1] 1 2 3

[1] 2.718282

[1] 1

In [11]:
# Angles are in radians.
sin(pi / 2)
cos(0)
tan(pi / 4)
asin(1)
acos(1)
atan(1)
sinh(1)
cosh(1)
tanh(1)
asinh(1)
acosh(2)
atanh(0.5)

[1] 1

[1] 1

[1] 1

[1] 1.570796

[1] 0

[1] 0.7853982

[1] 1.175201

[1] 1.543081

[1] 0.7615942

[1] 0.8813736

[1] 1.316958

[1] 0.5493061

Saving calculations

In [12]:
x1 = c(1, 2, 3, 4)
x2 = x1^2
x1
x2
x1 + sum(x1) * prod(c(1, 2))
abs(x1 - sum(x1) * prod(c(1, 2)))

[1] 1 2 3 4

[1]  1  4  9 16

[1] 21 22 23 24

[1] 19 18 17 16

Creating matrices

In [13]:
# Values fill down the columns by default.
x = matrix(data = 1:8, nrow = 4, ncol = 2)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [14]:
y = matrix(data = 1:8, nrow = 4, ncol = 2, byrow = TRUE)
y
x[3, 2]
y[3, 2]

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

[1] 7

[1] 6

Matrix properties

In [15]:
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)
is.matrix(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

[1] TRUE

Converting to a matrix

In [16]:
as.matrix(1:10)
data(warpbreaks)
is.matrix(warpbreaks)
warpbreaks[1:10, ]
as.matrix(warpbreaks[1:10, ])

      [,1]
 [1,]  1
 [2,]  2
 [3,]  3
 [4,]  4
 [5,]  5
 [6,]  6
 [7,]  7
 [8,]  8
 [9,]  9
[10,] 10

[1] FALSE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

In [17]:
help("matrix")