Week 4

Matrix operations and logical operators

Row and column names

In [1]:
x = matrix(data = 1:12, nrow = 4, ncol = 3)
rownames(x) = c("r1", "r2", "r3", "r4")
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

Constant and diagonal matrices

In [2]:
matrix(data = 2, nrow = 4, ncol = 2)
diag(1, nrow = 3, ncol = 3)
diag(5, nrow = 3, ncol = 3)

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Transpose

In [3]:
x = matrix(data = 1:8, nrow = 4, ncol = 2, byrow = TRUE)
x
t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Row and column totals

In [4]:
x = matrix(data = 1:8, nrow = 4, ncol = 2)
x
rowSums(x)
colSums(x)
rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

[1] 3 4 5 6

[1] 2.5 6.5

Selecting values

In [5]:
x = matrix(data = 1:15, nrow = 5, ncol = 3, byrow = TRUE)
x
x[3, ]
x[, 2]
x[4:5, 2:3]
x[c(1, 4), c(1, 3)]
x[, 2, drop = FALSE]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

     [,1] [,2]
[1,]  1    3
[2,] 10   12

     [,1]
[1,]  2
[2,]  5
[3,]  8
[4,] 11
[5,] 14

Calculations with constants

In [6]:
x = matrix(data = 1:8, nrow = 4, ncol = 2, byrow = TRUE)
x + 5
x - 5
5 * x
x / 2

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Adding and subtracting matrices

In [7]:
y = matrix(data = 11:18, nrow = 4, ncol = 2, byrow = TRUE)
x + y
x - y
x + 4 * x
4 * x - x

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

Matrix multiplication

In [8]:
y = matrix(data = 11:18, nrow = 2, ncol = 4, byrow = TRUE)
x %*% y
y %*% x

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [9]:
t(x) %*% x
x %*% t(x)
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Joining matrices

In [10]:
x = matrix(data = 1:6, nrow = 3, ncol = 2, byrow = TRUE)
y = matrix(data = 11:16, nrow = 3, ncol = 2, byrow = TRUE)
rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

Inverse and eigenvalues

In [11]:
y = matrix(c(84, 100, 100, 120), nrow = 2, byrow = TRUE)
y
solve(y)
round(y %*% solve(y), 8)
eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

     [,1] [,2]
[1,] 1    0
[2,] 0    1

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

Comparisons

In [12]:
8 > 7
7 < 5
7 >= 7
8 <= 8
7 == 7
8 != 9

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

In [13]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

Logical values

In [14]:
x = TRUE
y = FALSE
x & y
x | y
!x
xor(x, y)
as.logical(c(0, 1, -2))

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE  TRUE  TRUE

In [15]:
x = 5
logical1 = x > 2
logical2 = x < 10
logical3 = x != 5
logical1
logical2
logical3
is.logical(logical1)
2 * x > 11
3 * x < 20

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

And, or and filtering

In [16]:
x = 1:6
(x > 2) & (x < 5)
x[(x > 2) & (x < 5)]
(x > 2) | (x < 5)
x[(x > 2) | (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

In [17]:
x = c(8, 18)
(x < 10) | (x < 2)
(x < 10) & (x > 2)
# Use single values with && and || in current R.
(x[1] < 10) || (x[1] < 2)
(x[1] < 10) && (x[1] > 2)

[1]  TRUE FALSE

[1]  TRUE FALSE

[1] TRUE

[1] TRUE

In [18]:
x = 5
(x < 10) && (x > 2)
x = 15
(x < 10) && (x > 2)
x = 18
(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

[1] FALSE

Checking true and false

In [19]:
isTRUE(8 < 6)
isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE